apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.istio.gatewayName }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: piripak-credential
    hosts:
    - {{ .Values.istio.host }}
  
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.istio.serviceName }}
spec:
  hosts:
    - {{ .Values.istio.host }}
  gateways:
    - {{ .Values.istio.gatewayName }}
  http:
  - match:
    - uri:
        exact: /
    - uri:
        exact: /api/catalog
    route:
    - destination:
        host: {{ .Values.istio.destination }}
        port:
          number: {{ .Values.istio.port }}
