apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-volume
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: volume/storage/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      type: storage-volume