#!/bin/bash

PACKAGE_NAME=$1
PACKAGE_FOLDER="charts/$PACKAGE_NAME"
helm uninstall $PACKAGE_NAME
helm package $PACKAGE_FOLDER
helm install $PACKAGE_NAME $PACKAGE_NAME-0.1.0.tgz --values $PACKAGE_FOLDER/values.yaml